name: Deploy to GitHub Pages

on:
  workflow_dispatch: # This makes the workflow manually triggerable

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Persist npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: npm install

      - name: Debug API Key Variable
        run: echo "The API Key value is: $AIRTABLE_ARTHROPOD_API"
        env:
          AIRTABLE_ARTHROPOD_API: ${{ secrets.AIRTABLE_ARTHROPOD_API }}
          
      - name: Build Eleventy files
        env:
          AIRTABLE_ARTHROPOD_API: ${{ secrets.AIRTABLE_ARTHROPOD_API }}
        run: npx @11ty/eleventy --pathprefix=/arthropods/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
